# Generated by Django 5.0.7 on 2024-08-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(upload_to="blogs"),
        ),
    ]
